# Generated by Django 2.2.3 on 2019-07-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mainenu',
            new_name='MainName',
        ),
    ]
