# Generated by Django 2.2.3 on 2019-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190703_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='img',
        ),
    ]
