# Generated by Django 2.2.3 on 2019-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190705_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=255)),
                ('mainname', models.CharField(max_length=255)),
                ('portfolioname', models.CharField(max_length=255)),
                ('aboutname', models.CharField(max_length=255)),
                ('contactname', models.CharField(max_length=255)),
                ('footername', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio_img',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(default=' ', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
