# Generated by Django 2.2.3 on 2019-07-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190705_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='button',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='button_img',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='text',
        ),
        migrations.AddField(
            model_name='footer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Footer')),
            ],
        ),
    ]
