# Generated by Django 2.2.3 on 2019-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190705_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
